### ISSUE TITLE
logback configuration

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/buda-iiif-server#1]
There should be a system to configure logback so that when executing the jar we can override properties for the path to the log files, the log level, etc.

**Comment by MarcAgate** [comment]
Now running using PROD profile (it was running in local instead and therefore ignoring logback-spring.xml, since there was a typo in startup script - spring.profile.active instead of spring.profiles.active).
Currently, logs file are located in execution directory under /log/myhymir-iiif-server.log.
log levels are unchanged

**Comment by eroux** [comment]
great! can we move the log level to warn?

**Comment by MarcAgate** [comment]
Done as of commit 102afa5 
You can check loggers details at http://localhost:13581/monitoring/loggers

**Comment by eroux** [comment]
great! can you please create an `update.sh` script in buda-base and update the server on AWS?
