### ISSUE TITLE
aws credentials configuration

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/buda-iiif-server#14]
re: https://github.com/BuddhistDigitalResourceCenter/buda-base/issues/7 we should be able to have a way to [configure the aws credentials](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) in a file in `/etc/buda/iiifserv/`(it could in a properties file)

**Comment by eroux** [comment]
thanks!

**Comment by MarcAgate** [comment]
I think that aws config file should be common to all server instances and referenced to a single env variable. I suggest we put it in /etc/buda/aws/

**Comment by eroux** [comment]
well, I agree it's tempting to see it that way, but the config contains the geographical zone, and we could imagine have services in different zones (that happened in a project I had before)... and I think that would make the config slightly more difficult too. Maybe having the geographical zone in the property file of each project would be enough?

**Comment by MarcAgate** [comment]
The way we did it so far was to use two files (config -for the region- and credentials - for the keys) located in the .aws directory of the user default dir. With the new config (i.e an "external" credentials file, and no config file), we already set the region from a service properties file. 
However, in order to avoid any migration issue, it is certainly better to have each service not depending on a "global" config. Therefore, let's leave things the way they are now.
